import enum

class TypeOfInjury(enum.Enum):
   TAINT = 0
   PAPULE = 1
   PATCH = 2
   PLATE = 3
   NODULE = 4
   BLISTER = 5
   SORE = 6
   GALLBLADDER = 7

class ShapeOfInjury(enum.Enum):
   RING = 0
   DOME = 1
   OVAL = 2
   ROUND = 3
   UNDEFINED = 4
   ROLLED_UP = 5

class NumberOfInjuries(enum.Enum):
   LONELY = 0
   MULTIPLE = 1
   RECURRENT = 2
   DISSEMINATED = 3

class InjuryDistribution(enum.Enum):
   ASYMMETRIC = 0
   CONFLUENT = 1
   SYMMETRIC = 2
   SCATTERED = 3

class TypeOfDiagnosis(enum.Enum):
   AUTO = 0
   DOCTOR = 1

class BodyPart(enum.Enum):
   FOREHEAD = 0
   EYEBROWS = 1
   LEFT_EYEBROW = 2
   RIGHT_EYEBROW = 3
   EYES = 4
   LEFT_EYE = 5
   RIGHT_EYE = 6
   CHEEKBONES = 7
   LEFT_CHEEKBONE = 8
   RIGHT_CHEEKBONE = 9
   CHEEKS = 9
   LEFT_CHEEK = 10
   RIGHT_CHEEK = 11
   NOSE = 12
   LIPS = 13
   SUPERIOR_LIP = 14
   LOWER_LIP = 15
   CHIN = 16
   EARS = 17
   LEFT_EAR = 18
   RIGHT_EAR = 19
   FRONT_NECK = 20
   BACK_NECK = 21
   NAPE = 22
   SCALP = 23
   FRONT_LEFT_SHOULDER = 24
   FRONT_LEFT_BICEPS = 25
   FRONT_LEFT_FOREARM = 26
   BACK_LEFT_SHOULDER = 27
   BACK_LEFT_BICEPS = 28
   BACK_LEFT_ELBOW = 29
   BACK_LEFT_FOREARM = 30
   FRONT_RIGHT_SHOULDER = 31
   FRONT_RIGHT_BICEPS = 32
   FRONT_RIGHT_FOREARM = 33
   BACK_RIGHT_SHOULDER = 34
   BACK_RIGHT_BICEPS = 35
   BACK_RIGHT_ELBOW = 36
   BACK_RIGHT_FOREARM = 37
   LEFT_ANCKLE = 38
   LEFT_INSTEP = 39
   LEFT_TOES = 40
   LEFT_HEEL = 41
   LEFT_SOLE_OF_FOOT = 42
   RIGHT_ANCKLE = 43
   RIGHT_INSTEP = 44
   RIGHT_TOES = 45
   RIGHT_HEEL = 46
   RIGHT_SOLE_OF_FOOT = 47
   FRONT_LEFT_THIGH = 48
   FRONT_LEFT_KNEE = 49
   FRONT_LEFT_CALF = 50
   BACK_LEFT_THIGH = 51
   BACK_LEFT_GASTROCNEMIUS = 52
   FRONT_RIGHT_THIGH = 53
   FRONT_RIGHT_KNEE = 54
   FRONT_RIGHT_CALF = 55
   BACK_RIGHT_THIGH = 56
   BACK_RIGHT_GASTROCNEMIUS = 57
   CLAVICLE = 58
   CHEST = 59
   LEFT_PECTORAL = 60
   RIGHT_PECTORAL = 61
   ABDOMEN = 62
   RIGHT_LATERAL_ABDOMEN = 63
   LEFT_LATERAL_ABDOMEN = 64
   PELVIC_AREA = 65
   GENITALS = 66
   HIGH_BACK = 67
   LEFT_HIGH_BACK = 68
   RIGHT_HIGH_BACK = 69
   MEDIUM_BACK = 70
   LEFT_MEDIUM_BACK = 71
   RIGHT_MEDIUM_BACK = 72
   LOWER_BACK = 73
   LEFT_LOWER_BACK = 74
   RIGHT_LOWER_BACK = 75
   BUTTOCKS = 76
   LEFT_GLUTEUS = 77
   RIGHT_GLUTEUS = 78